fix(typescript): constrain extension types to Document
These functions were introduced to mongo.d.ts without constraint in
8ca07cc0d3d3051a6da9b4b432096ec1a039e3ee, which was included in Meteor
3.4 but not 3.3.

When this type definition is used (i.e. through zodern-types),
typescript will throw errors like:

```
.meteor/local/types/node_modules/package-types/mongo/package/os/packages/mongo/mongo.d.ts:125:63 - error TS2344: Type 'T' does not satisfy the constraint 'Document'.

125     addExtension<T = any, U = T>(extension: (this: Collection<T, U>, name: string | null, options?: CollectionOptions<T, U>) => void): void;
                                                                  ~

  .meteor/local/types/node_modules/package-types/mongo/package/os/packages/mongo/mongo.d.ts:125:18
    125     addExtension<T = any, U = T>(extension: (this: Collection<T, U>, name: string | null, options?: CollectionOptions<T, U>) => void): void;
                         ~~~~~~~
    This type parameter might need an `extends NpmModuleMongodb.BSON.Document` constraint.
```

The types should require that the type parameter to Collection extends
the mongo document type, so we add the additional suggested constraints,
which then satisfies the typechecker.